name: MinecartOnRailPlugin
version: 1.2
main: com.example.minecartplugin.MinecartOnRailPlugin
api-version: 1.21
author: Grok
description: A plugin that spawns a minecart when right-clicking a rail and removes it when the player exits.
softdepend: [ProtocolLib]
permissions:
  minecartplugin.userail:
    description: Allows players to spawn minecarts by right-clicking rails
    default: true